"""
Confluence DevOps Node - Studio Standard
Batch 47: Developer Tools & Ops
"""
from typing import Any, Dict, Optional, List
import aiohttp
import base64
import json
from ...base import BaseNode
from ...registry import register_node

@register_node("confluence_node")
class ConfluenceNode(BaseNode):
    """
    Manage Confluence pages and content.
    Supports: Create Page, Get Page, List Spaces, Search Content.
    """
    node_type = "confluence_node"
    version = "1.0.0"
    category = "devops"
    credentials_required = ["confluence_auth"]

    inputs = {
        "action": {
            "type": "dropdown",
            "default": "get_page",
            "options": ["create_page", "get_page", "list_spaces", "search_content"],
            "description": "Confluence action to perform"
        },
        "domain": {
            "type": "string",
            "required": True,
            "description": "Atlassian domain (e.g., 'company.atlassian.net')"
        },
        "space_key": {
            "type": "string",
            "optional": True,
            "description": "Space Key (e.g., 'DEV')"
        },
        "page_id": {
            "type": "string",
            "optional": True,
            "description": "Specific Page ID"
        },
        "payload": {
            "type": "json",
            "optional": True,
            "description": "Structured data for creation (title, content)"
        }
    }

    outputs = {
        "id": {"type": "string"},
        "url": {"type": "string"},
        "result": {"type": "any"}
    }

    async def execute(self, input_data: Any, context: Optional[Dict[str, Any]] = None) -> Dict[str, Any]:
        try:
            # 1. Resolve Auth
            creds = await self.get_credential("confluence_auth")
            email = None
            token = None
            domain = self.get_config("domain")
            
            if creds:
                email = creds.get("email")
                token = creds.get("api_token") or creds.get("token")
            
            if not email or not token:
                email = self.get_config("email")
                token = self.get_config("api_token")

            if not all([email, token, domain]):
                return {"status": "error", "error": "Confluence Email, API Token, and Domain are required."}

            # Auth Header
            auth_str = f"{email}:{token}"
            auth_b64 = base64.b64encode(auth_str.encode()).decode()
            headers = {
                "Authorization": f"Basic {auth_b64}",
                "Content-Type": "application/json",
                "Accept": "application/json"
            }

            action = self.get_config("action", "get_page")
            base_url = f"https://{domain}/wiki/rest/api"

            async with aiohttp.ClientSession() as session:
                if action == "create_page":
                    url = f"{base_url}/content"
                    space = self.get_config("space_key")
                    
                    data = self.get_config("payload", {})
                    if isinstance(input_data, dict):
                        data.update(input_data)
                    
                    title = data.get("title") or (input_data if isinstance(input_data, str) else "Untitled Studio Page")
                    content = data.get("content") or data.get("body") or "<p>Generated by Studio Agent</p>"
                    
                    if not space:
                         return {"status": "error", "error": "Space Key is required to create a page."}

                    payload = {
                        "type": "page",
                        "title": title,
                        "space": {"key": space},
                        "body": {
                            "storage": {
                                "value": content,
                                "representation": "storage"
                            }
                        }
                    }
                    async with session.post(url, json=payload, headers=headers) as resp:
                        result = await resp.json()
                        if resp.status >= 400:
                            return {"status": "error", "error": f"Confluence API Error: {result.get('message')}"}
                        
                        return {
                            "status": "success",
                            "data": {
                                "id": result.get("id"),
                                "url": f"https://{domain}/wiki{result.get('_links', {}).get('webui')}",
                                "result": result
                            }
                        }

                elif action == "get_page":
                    page_id = self.get_config("page_id") or (input_data if isinstance(input_data, str) and input_data.isdigit() else None)
                    if not page_id:
                         return {"status": "error", "error": "Page ID is required (numeric)."}
                    
                    url = f"{base_url}/content/{page_id}?expand=body.storage"
                    async with session.get(url, headers=headers) as resp:
                        result = await resp.json()
                        if resp.status >= 400:
                            return {"status": "error", "error": f"Confluence Error: {result.get('message')}"}
                        
                        return {
                            "status": "success",
                            "data": {
                                "id": result.get("id"),
                                "title": result.get("title"),
                                "result": result,
                                "content": result.get("body", {}).get("storage", {}).get("value")
                            }
                        }

                elif action == "list_spaces":
                    url = f"{base_url}/space"
                    async with session.get(url, headers=headers) as resp:
                        result = await resp.json()
                        if resp.status >= 400:
                             return {"status": "error", "error": "Could not list spaces."}
                        return {
                            "status": "success",
                            "data": {
                                "result": result,
                                "spaces": result.get("results", [])
                            }
                        }

                elif action == "search_content":
                    query = self.get_config("payload", {}).get("query") or (input_data if isinstance(input_data, str) else None)
                    if not query:
                         return {"status": "error", "error": "Search query is required."}
                    
                    url = f"{base_url}/content/search"
                    params = {"cql": f"text ~ \"{query}\""}
                    async with session.get(url, headers=headers, params=params) as resp:
                        result = await resp.json()
                        if resp.status >= 400:
                             return {"status": "error", "error": f"Search failed: {result.get('message')}"}
                        return {
                            "status": "success",
                            "data": {
                                "result": result,
                                "count": result.get("size", 0)
                            }
                        }

                return {"status": "error", "error": f"Unsupported action: {action}"}

        except Exception as e:
            return {"status": "error", "error": f"Confluence Node Failed: {str(e)}"}
